---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap
  labels:
    nac: "true"
data:
  examples:
    apply:
      repoUrl: https://victoriametrics.github.io/helm-charts/ 
      authSecret:
        name: test
        #keyUser: user
        #keyPass: password

      #path: './'
      #values:
        #test: a

