---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap
  labels:
    nac: "true"
data:
  bootstrap: |
    helm:
      repoUrl: https://gitlab.com/Exxog/testhelmchartfromgit
      path: bootstrapForNac/
      targetRevision: main
      #chart: 
      #path: './'
      values:
        test: a
