---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-sup
  label:
    nac: true
data:
  helm:
    victoria-metrics:
      repoUrl: https://victoriametrics.github.io/helm-charts/ 
      #chart: 
      #path: './'
      values:
        test: a

