---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-sup
  labels:
    nac: "true"
data:
  bootstrap: |
    helm:
      repoUrl: https://victoriametrics.github.io/helm-charts/ 
      #chart: 
      #path: './'
      values:
        test: a

