---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-sup
  labels:
    nac: "true"
data:
  bootstrap: |
    helm:
      repoUrl: https://gitlab.com/gitlab-org/charts/gitlab
      targetRevision: master
      #chart: 
      #path: './'
      values:
        test: a

